"""Regenerate the browser-side list of audio files that actually exist.

Run from the repository root after adding or removing audio:

    python scripts/generate-audio-manifest.py

The manifest lets the runtime use its existing synth fallback immediately
instead of issuing guaranteed 404 requests for optional music, ambience, or
sound-effect files that have not been supplied yet.
"""

from pathlib import Path
import json


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "js" / "audio-files.js"


def main() -> None:
    files = sorted(
        path.relative_to(ROOT).as_posix()
        for path in (ROOT / "assets" / "audio").rglob("*")
        if path.is_file() and path.suffix.lower() in {".mp3", ".wav", ".ogg", ".m4a"}
    )
    lines = [
        "/* Generated by scripts/generate-audio-manifest.py. */",
        "'use strict';",
        "VA.AudioFiles = new Set([",
        *(f"  {json.dumps(path)}," for path in files),
        "]);",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(files)} audio files")


if __name__ == "__main__":
    main()
